import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import SessionWrapper from './components/SessionWrapper'
import "../styles/globals.css";
import Navbars from './components/ืnavber';

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <SessionWrapper>
    <html lang="en">
      <body className={inter.className}>
        <Navbars />
        {children}
      </body>
    </html>
  </SessionWrapper>
  )
}
